### ISSUE TITLE
Fix JSON exception

### ISSUE THREAD

**Issue by knjk04** [knjk04/COVID-19-dashboard#5]
Sometimes, the following JSON exception is thrown:

```
Caused by: org.json.JSONException: A JSONObject text must begin with '{' at 1 [character 2 line 1]
	at org.json.JSONTokener.syntaxError(JSONTokener.java:507) ~[json-20200518.jar:na]
	at org.json.JSONObject.<init>(JSONObject.java:222) ~[json-20200518.jar:na]
	at org.json.JSONObject.<init>(JSONObject.java:406) ~[json-20200518.jar:na]
	at com.karankumar.covid19stats.backend.GlobalStats.fetchSummary(GlobalStats.java:38) ~[classes/:na]
	at com.karankumar.covid19stats.backend.GlobalStats.<init>(GlobalStats.java:24) ~[classes/:na]
	at com.karankumar.covid19stats.ui.views.global.GlobalView.<init>(GlobalView.java:31) ~[classes/:na]
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:na]
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[na:na]
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:200) ~[spring-beans-5.2.0.RELEASE.jar:5.2.0.RELEASE]
	... 74 common frames omitted
```

The culprit:

```java
JSONObject jsonObject = new JSONObject(data);
```

I have tried to print out the data (a String) before passing it into the `JSONObject` constructor, but it did not print before the exception was thrown.

File: GlobalStats.java

Branch: master and ui (and possibly fetch-json)

**Comment by knjk04** [comment]
Update: the following error message is displayed: 

`You have reached maximum request limit.`

The data has been cached now, so this shouldn't be a problem. The stack trace should not be displayed to the user, though.

**Comment by knjk04** [comment]
Handled by refreshing.
